# --- CONFIGURATION ---
$PromptFile  = ".\prompt.txt"
$LogFilePath = ".\agent_trace.log" # Adjust if your framework writes to a different filename

# 1. Read your long prompt from the file
if (-not (Test-Path $PromptFile)) {
    Write-Host "❌ Error: Prompt file '$PromptFile' not found. Please create it first." -ForegroundColor Red
    Exit
}
$LongPrompt = Get-Content $PromptFile -Raw
Write-Host "🚀 Loaded long prompt from file. Preparing to launch AGY Runner..." -ForegroundColor Cyan

# 2. Execute the agy runner command with your prompt
Write-Host "🤖 AGY Runner is now building your application. Please wait..." -ForegroundColor Yellow

# Replace 'agy run' with your framework's actual command line execution syntax if different
agy run --prompt $LongPrompt --log-output $LogFilePath

Write-Host "✅ Application creation sequence completed! Compiling token metrics...`n" -ForegroundColor Green

# 3. Parse the log file for token consumption per step
if (-not (Test-Path $LogFilePath)) {
    Write-Host "❌ Error: Token log file '$LogFilePath' was not generated by the runner." -ForegroundColor Red
    Exit
}

$TotalPrompt = 0
$TotalCompletion = 0
$OutputData = @()

Get-Content $LogFilePath | ForEach-Object {
    try {
        $Data = $_ | ConvertFrom-Json
        if ($null -ne $Data.step -and $null -ne $Data.metadata) {
            $StepNum    = $Data.step
            $Action     = if ($Data.action) { $Data.action } else { $Data.tool_name }
            $Prompt     = if ($Data.metadata.usage.prompt_tokens) { [int]$Data.metadata.usage.prompt_tokens } else { 0 }
            $Completion = if ($Data.metadata.usage.completion_tokens) { [int]$Data.metadata.usage.completion_tokens } else { 0 }
            $Total      = if ($Data.metadata.usage.total_tokens) { [int]$Data.metadata.usage.total_tokens } else { $Prompt + $Completion }
            
            $TotalPrompt     += $Prompt
            $TotalCompletion += $Completion
            
            $OutputData += [PSCustomObject]@{
                Step       = $StepNum
                Action     = $Action
                "Prompt Tokens" = $Prompt
                "Reply Tokens"  = $Completion
                "Total Step Tokens" = $Total
            }
        }
    } catch {}
}

# 4. Render results cleanly in the terminal window
$OutputData | Format-Table -AutoSize

Write-Host ("=" * 65)
Write-Host "📊 Total Context Sent (Prompt Tokens):     {0:N0}" -f $TotalPrompt
Write-Host "📊 Total Output Built (Completion Tokens): {0:N0}" -f $TotalCompletion
Write-Host "🚀 Grand Total Token Expense:              {0:N0}" -f ($TotalPrompt + $TotalCompletion) -ForegroundColor Green
Write-Host ("=" * 65)
