package com.dir2gpx.service

import android.util.Xml
import com.dir2gpx.model.GpxData
import com.dir2gpx.model.PointType
import com.dir2gpx.model.RoutePoint
import org.xmlpull.v1.XmlSerializer
import java.io.StringWriter
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

/**
 * Generates strict GPX 1.1 compliant XML documents from route data.
 *
 * Output follows the schema at http://www.topografix.com/GPX/1/1 and includes:
 * - `<metadata>` with route name and creation time
 * - `<wpt>` elements for named waypoints (Origin, Destination, Via)
 * - `<trk>` with a single `<trkseg>` containing all `<trkpt>` elements
 *
 * All timestamps use ISO 8601 UTC format: `YYYY-MM-DDTHH:MM:SSZ`
 */
object GpxSerializer {

    private const val GPX_NAMESPACE = "http://www.topografix.com/GPX/1/1"
    private const val XSI_NAMESPACE = "http://www.w3.org/2001/XMLSchema-instance"
    private const val SCHEMA_LOCATION =
        "http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"

    private val ISO_FORMATTER = DateTimeFormatter
        .ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'")
        .withZone(ZoneOffset.UTC)

    /**
     * Serializes route data into a GPX 1.1 XML string.
     *
     * @param waypoints Named waypoints (Origin, Via, Destination) for `<wpt>` elements.
     * @param trackPoints Ordered track points for `<trkseg>` → `<trkpt>` elements.
     * @param routeName Name for the route (used in `<metadata>` and `<trk>`).
     * @return A complete GPX 1.1 XML document as a string.
     */
    fun serialize(
        waypoints: List<RoutePoint>,
        trackPoints: List<RoutePoint>,
        routeName: String
    ): String {
        val writer = StringWriter()
        val serializer: XmlSerializer = Xml.newSerializer()

        serializer.setOutput(writer)
        serializer.startDocument("UTF-8", true)
        serializer.setFeature("http://xmlpull.org/v1/doc/features.html#indent-output", true)

        // <gpx> root element
        serializer.startTag(null, "gpx")
        serializer.attribute(null, "xmlns", GPX_NAMESPACE)
        serializer.attribute(null, "xmlns:xsi", XSI_NAMESPACE)
        serializer.attribute(null, "xsi:schemaLocation", SCHEMA_LOCATION)
        serializer.attribute(null, "version", "1.1")
        serializer.attribute(null, "creator", "Dir2GPX Android App")

        // <metadata>
        writeMetadata(serializer, routeName)

        // <wpt> elements
        for (waypoint in waypoints) {
            writeWaypoint(serializer, waypoint)
        }

        // <trk> with <trkseg>
        if (trackPoints.isNotEmpty()) {
            writeTrack(serializer, trackPoints, routeName)
        }

        // Close </gpx>
        serializer.endTag(null, "gpx")
        serializer.endDocument()

        return writer.toString()
    }

    private fun writeMetadata(serializer: XmlSerializer, routeName: String) {
        serializer.startTag(null, "metadata")

        serializer.startTag(null, "name")
        serializer.text(routeName)
        serializer.endTag(null, "name")

        serializer.startTag(null, "desc")
        serializer.text("Generated by Dir2GPX from Google Maps Directions URL")
        serializer.endTag(null, "desc")

        serializer.startTag(null, "time")
        serializer.text(formatTimestamp(Instant.now()))
        serializer.endTag(null, "time")

        serializer.endTag(null, "metadata")
    }

    private fun writeWaypoint(serializer: XmlSerializer, point: RoutePoint) {
        serializer.startTag(null, "wpt")
        serializer.attribute(null, "lat", formatCoordinate(point.latitude))
        serializer.attribute(null, "lon", formatCoordinate(point.longitude))

        // <name>
        if (point.name.isNotEmpty()) {
            serializer.startTag(null, "name")
            serializer.text(point.name)
            serializer.endTag(null, "name")
        }

        // <desc> with point type
        serializer.startTag(null, "desc")
        serializer.text(
            when (point.type) {
                PointType.ORIGIN -> "Route origin"
                PointType.DESTINATION -> "Route destination"
                PointType.VIA -> "Intermediate waypoint"
                PointType.TRACK -> "Track point"
            }
        )
        serializer.endTag(null, "desc")

        // <time>
        point.timestamp?.let { ts ->
            serializer.startTag(null, "time")
            serializer.text(formatTimestamp(ts))
            serializer.endTag(null, "time")
        }

        // <sym> for waypoint symbol
        serializer.startTag(null, "sym")
        serializer.text(
            when (point.type) {
                PointType.ORIGIN -> "Flag, Green"
                PointType.DESTINATION -> "Flag, Red"
                PointType.VIA -> "Pin, Blue"
                PointType.TRACK -> "Dot"
            }
        )
        serializer.endTag(null, "sym")

        serializer.endTag(null, "wpt")
    }

    private fun writeTrack(
        serializer: XmlSerializer,
        trackPoints: List<RoutePoint>,
        trackName: String
    ) {
        serializer.startTag(null, "trk")

        serializer.startTag(null, "name")
        serializer.text(trackName)
        serializer.endTag(null, "name")

        serializer.startTag(null, "trkseg")

        for (point in trackPoints) {
            serializer.startTag(null, "trkpt")
            serializer.attribute(null, "lat", formatCoordinate(point.latitude))
            serializer.attribute(null, "lon", formatCoordinate(point.longitude))

            // <ele> elevation (default 0.0 — we don't have elevation data)
            serializer.startTag(null, "ele")
            serializer.text("0.0")
            serializer.endTag(null, "ele")

            // <time>
            point.timestamp?.let { ts ->
                serializer.startTag(null, "time")
                serializer.text(formatTimestamp(ts))
                serializer.endTag(null, "time")
            }

            serializer.endTag(null, "trkpt")
        }

        serializer.endTag(null, "trkseg")
        serializer.endTag(null, "trk")
    }

    /**
     * Formats a coordinate value with 7 decimal places (sub-meter precision).
     */
    private fun formatCoordinate(value: Double): String {
        return "%.7f".format(value)
    }

    /**
     * Formats an Instant as ISO 8601 UTC timestamp.
     */
    private fun formatTimestamp(instant: Instant): String {
        return ISO_FORMATTER.format(instant)
    }
}
